test_batch_size: 100
dataset: wn18rr
task: all
DirectAU-KG:
  optimizer: Adagrad
  learning_rate: 0.1
  dim: 50
  gamma: 1.0
  n_epoch: 1000
  batch_size: 3536
  epoch_per_test: 10
  model_file: DirectAU-DistMult.mdl
DistMult:
  optimizer: Adagrad
  learning_rate: 0.1
  dim: 50
  margin: 1.0
  temp: 1.0
  n_epoch: 1000
  batch_size: 3536
  epoch_per_test: 10
  model_file: DistMult.mdl
log:
  dump_config: false
  to_file: true
  dir: ./log
  prefix: ""