g_config: DistMult
d_config: TransE
test_batch_size: 100
dataset: fb15k237
task: all
KBGAN:
  class_rank_balance: 1.0
  early_stop_patience: -1
  temperature: 1.0
  n_sample: 20
  n_epoch: 5000
  n_batch: 100
  epoch_per_test: 100
TransE:
  optimizer: Adagrad
  learning_rate: 0.01
  dim: 50
  margin: 3
  p: 1
  temp: 1
  n_epoch: 1000
  n_batch: 100
  epoch_per_test: 50
  model_file: TransE.mdl
TransD:
  optimizer: Adagrad
  learning_rate: 0.01
  dim: 50
  margin: 3
  p: 1
  temp: 1
  n_epoch: 1000
  n_batch: 100
  epoch_per_test: 50
  model_file: TransD.mdl
DistMult:
  optimizer: Adagrad
  learning_rate: 0.01
  dim: 50
  lam: 1
  sigma: 0.2
  n_sample: 20
  sample_freq: 1
  n_epoch: 1000
  n_batch: 100
  epoch_per_test: 50
  model_file: DistMult.mdl
ComplEx:
  optimizer: Adagrad
  learning_rate: 0.01
  dim: 25
  lam: 1
  sigma: 0.2
  n_sample: 20
  sample_freq: 1
  n_epoch: 1000
  n_batch: 100
  epoch_per_test: 50
  model_file: ComplEx.mdl
log:
  dump_config: false
  to_file: true
  dir: ./log
  prefix: ""