test_batch_size: 10
dataset: wn18rr
task: all
DirectAU_KG:
  optimizer: Adam
  learning_rate: 0.005
  dim: 50
  gamma: 1.0
  n_epoch: 20
  batch_size: 256
  epoch_per_test: 5
  model_file: DirectAU.mdl
TransE:
  optimizer: Adam
  learning_rate: 0.005
  dim: 50
  margin: 1.0
  p: 2
  temp: 1.0
  n_epoch: 20
  batch_size: 256
  epoch_per_test: 5
  model_file: TransE.mdl
log:
  dump_config: false
  to_file: true
  dir: ./log
  prefix: ""