test_batch_size: 10
dataset: wn18rr
task: all
DirectAUKG:
  optimizer: Adam
  learning_rate: 0.005
  weight_decay: 0.0
  inverse_train: 0.0
  dim: 50
  gamma_h: 0.1
  gamma_t: 0.1
  gamma_all_e: 0.1
  compose_mode: mul
  n_epoch: 20
  batch_size: 256
  epoch_per_test: 5
  model_file: DirectAUKG.mdl
TransE:
  optimizer: Adam
  learning_rate: 0.005
  dim: 50
  margin: 3
  p: 1
  temp: 1
  n_epoch: 20
  batch_size: 256
  epoch_per_test: 5
  model_file: TransE.mdl
log:
  dump_config: false
  to_file: true
  dir: ./log
  prefix: ""