test_batch_size: 100
dataset: wn18rr
task: all
DirectAU-KG:
  optimizer: SGD
  learning_rate: 0.01
  dim: 50
  gamma: 0.1
  n_epoch: 1000
  batch_size: 200
  epoch_per_test: 10
  model_file: DirectAU-TransE.mdl
TransE:
  optimizer: SGD
  learning_rate: 0.01
  dim: 100
  margin: 2.0
  p: 2
  temp: 1.0
  n_epoch: 1000
  batch_size: 200
  epoch_per_test: 10
  model_file: TransE.mdl
log:
  dump_config: false
  to_file: true
  dir: ./log
  prefix: ""