test_batch_size: 50
dataset: wn18rr
task: all
DirectAU-KG:
  optimizer: Adadelta
  learning_rate: 0.005
  dim: 50
  relation_dim: 50
  temp: 1.0
  gamma: 1.0
  n_epoch: 1000
  batch_size: 200
  epoch_per_test: 10
  model_file: DirectAU-TransD.mdl
TransD:
  optimizer: Adadelta
  learning_rate: 0.005
  dim: 50
  relation_dim: 50
  margin: 1.0
  p: 2
  temp: 1.0
  n_epoch: 1000
  batch_size: 200
  epoch_per_test: 10
  model_file: TransD.mdl
log:
  dump_config: false
  to_file: true
  dir: ./log
  prefix: ""